OUTFILE="musicpp-implementation.hpp"

(
	cd src
	echo "// This file was autogenerated by $0, DO NOT TOUCH, as changes will be overwritten" > $OUTFILE
	for file in $(find musicpp/ -name '*.cpp'); do
		printf '#include "%s"\n' "${file}" >> $OUTFILE
	done
)
