// This file was autogenerated by ./tools/generate_musicpp_implementation_hpp.sh, DO NOT TOUCH, as changes will be overwritten
#include "musicpp/Note.cpp"
#include "musicpp/Rhythm.cpp"
#include "musicpp/analysis/Analysis.cpp"
